# For mikrus / docker-compose.yml
services:
  app:
    image: ghcr.io/janmadon/automessager:latest
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .env:/var/www/html/.env
    networks:
      - laravel
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - laravel
    depends_on:
      - app
    # Nginx potrzebuje dostępu do plików statycznych z app
    volumes_from:
      - app:ro

  db:
    image: alpine:latest
    container_name: laravel_db_placeholder
    command: tail -f /dev/null
    networks:
      - laravel

  mail:
    image: axllent/mailpit:latest
    container_name: laravel_mail
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
